In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(
    "datasets/hourly_weather_dataset.csv"
)

df.head()

,date,0-hour,1-hour,2-hour,3-hour,4-hour,5-hour,6-hour,7-hour,8-hour,...,14-hour,15-hour,16-hour,17-hour,18-hour,19-hour,20-hour,21-hour,22-hour,23-hour
0,2025-04-01,27.6,26.8,26.2,25.4,24.6,23.9,23.8,24.4,26.5,...,34.5,34.1,33.8,32.7,31.8,31.0,30.0,29.2,28.6,27.4
1,2025-04-02,26.1,25.1,24.5,24.0,23.8,23.5,23.3,24.0,26.0,...,32.8,32.5,32.2,31.2,30.9,30.3,29.4,28.5,27.6,27.0
2,2025-04-03,26.8,25.6,25.0,24.8,24.4,24.2,21.9,21.5,23.1,...,29.9,30.2,28.9,28.4,24.5,24.4,24.0,24.0,23.9,23.8
3,2025-04-04,21.6,21.7,21.6,21.9,21.5,21.4,22.2,22.8,24.1,...,30.5,30.3,27.6,28.0,28.5,27.1,26.5,26.0,25.6,25.2
4,2025-04-05,24.9,24.5,24.1,24.0,23.8,23.5,23.8,24.5,26.4,...,32.5,32.3,32.2,31.5,30.4,28.9,27.8,26.9,26.2,26.0

In [5]:
print(df.shape)
print(df.dtypes)
df.isnull().sum()

(61, 25)
date           str
0-hour     float64
1-hour     float64
2-hour     float64
3-hour     float64
4-hour     float64
5-hour     float64
6-hour     float64
7-hour     float64
8-hour     float64
9-hour     float64
10-hour    float64
11-hour    float64
12-hour    float64
13-hour    float64
14-hour    float64
15-hour    float64
16-hour    float64
17-hour    float64
18-hour    float64
19-hour    float64
20-hour    float64
21-hour    float64
22-hour    float64
23-hour    float64
dtype: object

date       0
0-hour     0
1-hour     0
2-hour     0
3-hour     0
4-hour     0
5-hour     0
6-hour     0
7-hour     0
8-hour     0
9-hour     0
10-hour    0
11-hour    0
12-hour    0
13-hour    0
14-hour    0
15-hour    0
16-hour    0
17-hour    0
18-hour    0
19-hour    0
20-hour    0
21-hour    0
22-hour    0
23-hour    0
dtype: int64

In [6]:
df["date"] = pd.to_datetime(
    df["date"]
)

In [7]:
hour_columns = [
    f"{hour}-hour"
    for hour in range(24)
]
df["avg_temp"] = (
    df[hour_columns]
    .mean(axis=1)
)

In [8]:
df["daily_max"] = (
    df[hour_columns]
    .max(axis=1)
)

In [9]:
df["daily_min"] = (
    df[hour_columns]
    .min(axis=1)
)

In [10]:
df["temp_range"] = (
    df["daily_max"]
    -
    df["daily_min"]
)

In [11]:
df["month"] = (
    df["date"]
    .dt.month_name()
)

df["day"] = (
    df["date"]
    .dt.day
)

df["weekday"] = (
    df["date"]
    .dt.day_name()
)

In [13]:
df.describe()

,date,0-hour,1-hour,2-hour,3-hour,4-hour,5-hour,6-hour,7-hour,8-hour,...,19-hour,20-hour,21-hour,22-hour,23-hour,avg_temp,daily_max,daily_min,temp_range,day
count,61,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,...,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000
mean,2025-05-01 00:00:00,27.629508,26.926230,26.362295,25.919672,25.542623,25.221311,25.368852,26.295082,28.019672,...,31.449180,30.680328,29.919672,29.172131,28.449180,30.024044,35.195082,24.957377,10.237705,15.754098
min,2025-04-01 00:00:00,21.600000,21.700000,21.600000,21.900000,21.500000,21.400000,21.900000,21.500000,23.100000,...,24.000000,24.000000,24.000000,23.900000,23.800000,25.287500,28.000000,21.400000,4.200000,1.000000
25%,2025-04-16 00:00:00,26.100000,25.300000,25.000000,24.500000,24.500000,23.900000,24.200000,24.900000,26.400000,...,29.400000,28.100000,27.700000,27.300000,27.000000,28.608333,33.500000,23.800000,8.900000,8.000000
50%,2025-05-01 00:00:00,28.000000,27.100000,26.300000,25.800000,25.300000,25.100000,25.400000,26.500000,28.500000,...,32.300000,31.300000,30.500000,29.800000,29.000000,30.750000,36.000000,25.000000,10.600000,16.000000
75%,2025-05-16 00:00:00,29.000000,28.400000,27.800000,27.100000,26.500000,26.000000,26.400000,27.600000,29.500000,...,33.500000,33.000000,32.100000,31.100000,30.000000,31.437500,37.100000,26.000000,11.900000,23.000000
max,2025-05-31 00:00:00,31.400000,30.400000,29.900000,29.600000,29.200000,28.900000,29.200000,29.800000,32.000000,...,35.800000,34.900000,33.900000,32.800000,32.200000,33.637500,38.700000,28.900000,13.600000,31.000000
std,NaN,2.177563,1.972553,1.830771,1.671010,1.592949,1.485610,1.556121,1.789360,2.074353,...,3.055521,2.998267,2.820332,2.588831,2.325269,2.255694,2.837688,1.529211,2.054845,8.880045

In [15]:
hottest=df.loc[df["avg_temp"].idxmax()]
print(hottest)

coldest=df.loc[df["avg_temp"].idxmin()]
print(coldest)

date          2025-04-24 00:00:00
0-hour                       31.4
1-hour                       30.4
2-hour                       29.8
3-hour                       29.2
4-hour                       28.8
5-hour                       27.8
6-hour                       28.5
7-hour                       29.8
8-hour                       32.0
9-hour                       34.2
10-hour                      35.6
11-hour                      36.9
12-hour                      37.4
13-hour                      38.2
14-hour                      38.6
15-hour                      38.7
16-hour                      38.0
17-hour                      36.9
18-hour                      36.2
19-hour                      35.2
20-hour                      34.9
21-hour                      33.9
22-hour                      32.7
23-hour                      32.2
avg_temp                  33.6375
daily_max                    38.7
daily_min                    27.8
temp_range                   10.9
month                       April
day                            24
weekday                  Thursday
Name: 23, dtype: object
date          2025-05-28 00:00:00
0-hour                       24.2
1-hour                       24.1
2-hour                       24.1
3-hour                       24.0
4-hour                       23.9
5-hour                       23.9
6-hour                       23.8
7-hour                       23.8
8-hour                       24.2
9-hour                       25.1
10-hour                      26.5
11-hour                      27.7
12-hour                      28.0
13-hour                      28.0
14-hour                      27.1
15-hour                      26.6
16-hour                      26.8
17-hour                      26.1
18-hour                      26.9
19-hour                      25.8
20-hour                      24.5
21-hour                      24.0
22-hour                      23.9
23-hour                      23.9
avg_temp                  25.2875
daily_max                    28.0
daily_min                    23.8
temp_range                    4.2
month                         May
day                            28
weekday                 Wednesday
Name: 57, dtype: object

In [16]:
df.groupby(
    "month"
)["avg_temp"].mean()

month
April    30.645278
May      29.422849
Name: avg_temp, dtype: float64

In [17]:
long_df = pd.melt(
    df,
    id_vars=["date"],
    value_vars=hour_columns,
    var_name="hour",
    value_name="temperature",
)

In [20]:
long_df.groupby(
    "hour"
)["temperature"].mean()

hour
0-hour     27.629508
1-hour     26.926230
10-hour    31.750820
11-hour    33.127869
12-hour    34.137705
13-hour    34.813115
14-hour    34.932787
15-hour    34.685246
16-hour    34.247541
17-hour    33.596721
18-hour    32.337705
19-hour    31.449180
2-hour     26.362295
20-hour    30.680328
21-hour    29.919672
22-hour    29.172131
23-hour    28.449180
3-hour     25.919672
4-hour     25.542623
5-hour     25.221311
6-hour     25.368852
7-hour     26.295082
8-hour     28.019672
9-hour     29.991803
Name: temperature, dtype: float64

In [18]:
df[hour_columns].corr()

,0-hour,1-hour,2-hour,3-hour,4-hour,5-hour,6-hour,7-hour,8-hour,9-hour,...,14-hour,15-hour,16-hour,17-hour,18-hour,19-hour,20-hour,21-hour,22-hour,23-hour
0-hour,1.000000,0.970477,0.944651,0.910595,0.884869,0.866312,0.745530,0.752305,0.753830,0.753661,...,0.757146,0.743862,0.766036,0.741014,0.709508,0.723373,0.738932,0.735018,0.742312,0.751704
1-hour,0.970477,1.000000,0.986490,0.948016,0.921611,0.886417,0.788827,0.794082,0.789220,0.778987,...,0.766311,0.746526,0.778770,0.762982,0.724745,0.739404,0.747071,0.737873,0.749828,0.761697
2-hour,0.944651,0.986490,1.000000,0.975272,0.954558,0.919175,0.815451,0.812593,0.789412,0.758344,...,0.729169,0.710728,0.747118,0.727675,0.695464,0.706605,0.713211,0.704465,0.721010,0.737693
3-hour,0.910595,0.948016,0.975272,1.000000,0.987533,0.959223,0.857002,0.832074,0.792286,0.741337,...,0.699372,0.681039,0.719063,0.698274,0.665482,0.677010,0.684824,0.673472,0.693539,0.711916
4-hour,0.884869,0.921611,0.954558,0.987533,1.000000,0.972706,0.864060,0.831491,0.778970,0.719200,...,0.665970,0.641270,0.682324,0.663588,0.629470,0.642083,0.650257,0.638113,0.658452,0.682014
5-hour,0.866312,0.886417,0.919175,0.959223,0.972706,1.000000,0.872488,0.834097,0.765678,0.695915,...,0.636109,0.620472,0.664726,0.645526,0.613820,0.625925,0.641542,0.630778,0.646501,0.666707
6-hour,0.745530,0.788827,0.815451,0.857002,0.864060,0.872488,1.000000,0.974579,0.913674,0.833116,...,0.710880,0.673076,0.714498,0.700265,0.703244,0.708074,0.727522,0.711274,0.707524,0.713591
7-hour,0.752305,0.794082,0.812593,0.832074,0.831491,0.834097,0.974579,1.000000,0.969287,0.900588,...,0.785949,0.742480,0.783153,0.773709,0.764221,0.763902,0.777183,0.766478,0.765528,0.772878
8-hour,0.753830,0.789220,0.789412,0.792286,0.778970,0.765678,0.913674,0.969287,1.000000,0.969801,...,0.874966,0.829567,0.857659,0.848375,0.821280,0.817502,0.819373,0.809968,0.805047,0.808211
9-hour,0.753661,0.778987,0.758344,0.741337,0.719200,0.695915,0.833116,0.900588,0.969801,1.000000,...,0.939328,0.897914,0.911066,0.907149,0.874772,0.870467,0.861645,0.852873,0.842145,0.839904
10-hour,0.734540,0.757043,0.730631,0.702914,0.677751,0.651021,0.779811,0.853976,0.935137,0.988179,...,0.949241,0.910300,0.920115,0.919072,0.887082,0.881543,0.865084,0.856928,0.846076,0.842538
11-hour,0.715797,0.739017,0.708527,0.676840,0.651395,0.621248,0.750838,0.827265,0.911490,0.972374,...,0.952394,0.913618,0.918920,0.920289,0.896002,0.889561,0.869270,0.861597,0.853816,0.848192
12-hour,0.733714,0.750633,0.715698,0.685191,0.655807,0.624372,0.731730,0.807789,0.890464,0.954487,...,0.965866,0.936480,0.939997,0.942225,0.910277,0.903512,0.880973,0.875032,0.872529,0.864622
13-hour,0.749074,0.761551,0.724685,0.693486,0.660790,0.625527,0.716406,0.792561,0.877548,0.944319,...,0.982452,0.954096,0.951494,0.951534,0.920998,0.916268,0.894448,0.887974,0.882637,0.872870
14-hour,0.757146,0.766311,0.729169,0.699372,0.665970,0.636109,0.710880,0.785949,0.874966,0.939328,...,1.000000,0.967684,0.961270,0.958797,0.918471,0.911143,0.893972,0.885430,0.874636,0.865133
15-hour,0.743862,0.746526,0.710728,0.681039,0.641270,0.620472,0.673076,0.742480,0.829567,0.897914,...,0.967684,1.000000,0.975682,0.958421,0.902145,0.895043,0.885185,0.882178,0.873023,0.867333
16-hour,0.766036,0.778770,0.747118,0.719063,0.682324,0.664726,0.714498,0.783153,0.857659,0.911066,...,0.961270,0.975682,1.000000,0.986645,0.909909,0.905297,0.888465,0.883133,0.876324,0.870371
17-hour,0.741014,0.762982,0.727675,0.698274,0.663588,0.645526,0.700265,0.773709,0.848375,0.907149,...,0.958797,0.958421,0.986645,1.000000,0.921421,0.917298,0.895994,0.890022,0.883143,0.872847
18-hour,0.709508,0.724745,0.695464,0.665482,0.629470,0.613820,0.703244,0.764221,0.821280,0.874772,...,0.918471,0.902145,0.909909,0.921421,1.000000,0.989629,0.970901,0.963438,0.946333,0.930228
19-hour,0.723373,0.739404,0.706605,0.677010,0.642083,0.625925,0.708074,0.763902,0.817502,0.870467,...,0.911143,0.895043,0.905297,0.917298,0.989629,1.000000,0.988617,0.980284,0.963718,0.949819
20-hour,0.738932,0.747071,0.713211,0.684824,0.650257,0.641542,0.727522,0.777183,0.819373,0.861645,...,0.893972,0.885185,0.888465,0.895994,0.970901,0.988617,1.000000,0.994949,0.976222,0.961087
21-hour,0.735018,0.737873,0.704465,0.673472,0.638113,0.630778,0.711274,0.766478,0.809968,0.852873,...,0.885430,0.882178,0.883133,0.890022,0.963438,0.980284,0.994949,1.000000,0.986376,0.968027
22-hour,0.742312,0.749828,0.721010,0.693539,0.658452,0.646501,0.707524,0.765528,0.805047,0.842145,...,0.874636,0.873023,0.876324,0.883143,0.946333,0.963718,0.976222,0.986376,1.000000,0.989894
23-hour,0.751704,0.761697,0.737693,0.711916,0.682014,0.666707,0.713591,0.772878,0.808211,0.839904,...,0.865133,0.867333,0.870371,0.872847,0.930228,0.949819,0.961087,0.968027,0.989894,1.000000

In [19]:
df.sort_values(
    by="avg_temp",
    ascending=False,
).head(10)

,date,0-hour,1-hour,2-hour,3-hour,4-hour,5-hour,6-hour,7-hour,8-hour,...,21-hour,22-hour,23-hour,avg_temp,daily_max,daily_min,temp_range,month,day,weekday
23,2025-04-24,31.4,30.4,29.8,29.2,28.8,27.8,28.5,29.8,32.0,...,33.9,32.7,32.2,33.637500,38.7,27.8,10.9,April,24,Thursday
24,2025-04-25,31.2,30.4,29.9,29.6,29.2,28.9,29.2,29.6,31.2,...,33.2,32.0,31.2,33.429167,38.4,28.9,9.5,April,25,Friday
21,2025-04-22,30.5,30.0,29.5,28.7,28.1,27.7,28.0,29.3,31.5,...,33.5,32.7,32.0,33.258333,38.5,27.7,10.8,April,22,Tuesday
22,2025-04-23,30.8,29.5,29.0,28.8,28.5,28.0,28.3,29.4,30.9,...,33.2,32.4,31.9,33.170833,38.3,28.0,10.3,April,23,Wednesday
19,2025-04-20,28.9,28.4,28.3,27.9,27.5,27.2,28.0,29.2,31.2,...,32.8,32.3,31.0,32.758333,37.8,27.2,10.6,April,20,Sunday
20,2025-04-21,30.0,29.2,28.5,27.6,27.0,26.7,27.0,28.1,30.0,...,32.8,31.8,31.0,32.416667,37.8,26.7,11.1,April,21,Monday
25,2025-04-26,30.4,29.5,29.5,29.1,28.1,27.5,27.0,28.3,30.0,...,32.4,31.8,30.9,32.383333,37.5,27.0,10.5,April,26,Saturday
32,2025-05-03,29.0,28.2,27.6,27.1,26.9,27.0,26.1,27.8,29.8,...,31.4,31.5,31.0,32.300000,38.5,26.1,12.4,May,3,Saturday
29,2025-04-30,29.5,28.8,27.8,26.8,26.0,25.6,26.9,28.4,30.6,...,32.2,30.9,29.0,32.258333,38.4,25.6,12.8,April,30,Wednesday
31,2025-05-02,29.2,28.0,27.2,26.6,26.2,25.8,25.5,26.5,28.5,...,33.2,31.1,30.0,32.179167,38.7,25.5,13.2,May,2,Friday